# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170320_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='home_display',
            field=models.BooleanField(default=False, verbose_name='首页显示'),
        ),
        migrations.AddField(
            model_name='article',
            name='nav_display',
            field=models.BooleanField(default=False, verbose_name='导航显示'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='网址'),
        ),
    ]
