# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170320_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(db_index=True, max_length=200, verbose_name='网址'),
        ),
    ]
